name: Publish
on:
  push:
    branches:
      - master
      - updates
      - bugs/assemblyVersionTroubles
      - dotnet8
    paths:
      - RELEASE_NOTES.md
      - .github/workflows/publish.yml
jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.400'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      - name: Build and Pack
        shell: cmd
        run: build.cmd -t Pack
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: bin\*.nupkg
      - name: NuGet
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: cmd
        run: dotnet nuget push "bin\*.nupkg" -k %NUGET_KEY% -s "https://api.nuget.org/v3/index.json" --skip-duplicate
